# Exercici 1
#### Descarrega el data set Airlines Delay: Airline on-time statistics and delay causes i carrega’l a un Pandas Dataframe. Explora les dades que conté, explica breument quines variables hi ha i queda’t únicament amb les columnes que consideris rellevants. Justifica la teva elecció.

#### Airlines Delay: Airline on-time statistics and delay causes

## Important

#### Redueix la dimensió del dataset de manera aleatòria per tal d'obtenir un dataset de només 200.000 registres. Tots els exercicis s'han de fer amb aquest dataset reduït.

In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('C:/RAUL/NISSAN/GENERAL/USB/FORMACION/BootCamp - Data Scientist_Analist/IT Academy Cibernarium - Data Science/Data Science Itinerario/3.- Programación numerica, dataframes y análisis estadístico/Entrega/DelayedFlights.csv')

In [3]:
#Netejem les columnes que no volem
df = df.drop(['Unnamed: 0', 'Year', 'DayofMonth', 'TaxiIn', 'CRSDepTime', 'TaxiOut', 'CRSArrTime', 'TailNum', 
              'ActualElapsedTime', 'CRSElapsedTime', 'ArrTime', 'DepTime' ],1)

C:\Users\rauga\AppData\Local\Temp\ipykernel_7500\4066909782.py:2: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only.
  df = df.drop(['Unnamed: 0', 'Year', 'DayofMonth', 'TaxiIn', 'CRSDepTime', 'TaxiOut', 'CRSArrTime', 'TailNum',

In [4]:
df_retallat= df.sample(n=200000) # Mostra aleatòria de 200000 files
df_retallat.shape

(200000, 18)

In [5]:
df_retallat.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 200000 entries, 470777 to 145185
Data columns (total 18 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   Month              200000 non-null  int64
 1   DayOfWeek          200000 non-null  int64
 2   UniqueCarrier      200000 non-null  object
 3   FlightNum          200000 non-null  int64
 4   AirTime            199130 non-null  float64
 5   ArrDelay           199130 non-null  float64
 6   DepDelay           200000 non-null  float64
 7   Origin             200000 non-null  object
 8   Dest               200000 non-null  object
 9   Distance           200000 non-null  int64
 10  Cancelled          200000 non-null  int64
 11  CancellationCode   200000 non-null  object
 12  Diverted           200000 non-null  int64
 13  CarrierDelay       128989 non-null  float64
 14  WeatherDelay       128989 non-null  float64
 15  NASDelay           128989 non-null  float64
 16  SecurityDelay      128989 non-null  float64
 17  LateAircraftDelay  128989 non-null  float64
dtypes: float64(8), int64(6), object(4)
memory usage: 29.0+ MB

## Columnes seleccionades:

* **Month**: 1-12
* **UniqueCarrier**: Codi del Carrier
* **FlightNum**: número del vol

* **AirTime**: durada del vol en minuts
* **ArrDelay**: retràs d'arribada, en minuts. Un vol es considera que ha arribat a temps si opera menys de 15 minuts més tard del temps programat que es mostra als carries' Computerized Reservations Systems (CRS).
    * Es pot calcular com aquesta suma: CarrierDelay + WeatherDelay + NASDelay + SecurityDelay + LateAircraftDelay
    * També es pot calcular com la resta: ArrTime - CRSArrTime quan les altres columnes estàn vuides però això és degut a vols cancel.lats o desviats.

* **DepDelay**: retràs de sortida, in minutes
* **Origin**: codi IATA de l'aeroport d'origen
* **Dest**: codi IATA de l'aeroport de destí
* **Distance**: en milles

* **Cancelled**: vol cancel.lat (0/1) --> informació reduntant que es pot extreure del CancellationCode
* **CancellationCode**: motiu de la cancel.lació (A = carrier, B = climatologia, C = National Airspace System (NAS), D = seguretat)

* **Diverted**: vol desviat --> 1 = yes, 0 = no
* **CarrierDelay**: en minuts. Enrederiment de companyia. Per exemple: neteja de l'avió, reparació de danys de l'avió, espera per passatjers o tripulants de l'avió, equipatje, inspeccions de l'avió,...
* **WeatherDelay**: en minuts. Enredariments deguts a condicions meteorològiques complicades, que poden afectar la sortida, la ruta del vol o l'arribada.
* **NASDelay** en minuts. Enredariments controlats per la National Airspace System (NAS), pot incloure: condicions meteorològiques no extremes, operacions de l'aeroport, volum elevat de tràfic aeri, control de tràfic aèri,... etc.
* **SecurityDelay** en minuts: Enrederiment causat per evacuació de la terminal, concurse Security delay is caused by evacuation of a terminal or concurrència, reembarcament de l'avió per motius de seguretat,...
* **LateAircraftDelay** en minuts. Enredariments deguts a enrederiments del mateix avió amb vols anteriors que es van arrossegant durant el dia.

## Columnes descartades:
* **Year**: 2008 -->Totes les dades són del 2008, per tant no és una dada rellevant
* **DayOfWeek**: 1 (Dilluns) - 7 (Diumenge) --> no fa cap aportació rellevant
* **DayofMonth**: 1-31 --> en principi no aporta cap informació destacable pel seu anàlisis
* **ArrTime**: hora real d'arribada del vol (hora local - hhmm) --> Informació innecesària o redundant
* **DepTime**: hora real de sortida del vol (hora local - hhmm) --> Informació innecesària o redundant
* **CRSDepTime**: hora planificada de sortida del vol (hora local - hhmm) --> Informació innecesària o redundant
* **CRSArrTime**: hora planificada d'arribada del vol (hora local - hhmm) --> Informació innecesària o redundant
* **TailNum**: matrícula del avió --> Informació innecesàrea per fer l'estudi
* **TaxiIn**: taxi in time, en minuts (deduixo que és el temps per omplir l'avió de passatgers) --> Informació poc interessant per fer l'estudi
* **TaxiOut**: taxi out time en minuts (deduixo que és el temps per buidar l'avió de passatgers)--> Informació poc interessant per fer l'estudi
* **ActualElapsedTime**: en minuts, és el temps real entre la sortida i l'arribada --> AirTime+TaxiIn+TaxiOut, però també és igual al ArrTime-DepTime.
* **CRSElapsedTime**: en minuts , és el temps teóric entre la sortida i l'arribada --> AirTime+TaxiIn+TaxiOut amb valors teórics que no surten a la taula, però també és igual al CRSArrTime-CRSDepTime que sí que surten a la taula.

# Exercici 2
#### Fes un informe complet del dataset:

* Resumeix estadísticament el dataset i les columnes d’interès.

In [60]:
df_retallat.describe().round(1)

,Month,DayOfWeek,FlightNum,AirTime,ArrDelay,DepDelay,Distance,Cancelled,Diverted,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay
count,200000.0,200000.0,200000.0,199130.0,199130.0,200000.0,200000.0,200000.0,200000.0,128989.0,128989.0,128989.0,128989.0,128989.0
mean,6.1,4.0,2186.6,108.2,42.2,43.2,765.0,0.0,0.0,19.1,3.7,15.1,0.1,25.3
std,3.5,2.0,1948.7,68.8,56.7,53.2,575.1,0.0,0.1,43.2,21.6,34.0,2.0,41.9
min,1.0,1.0,1.0,0.0,-53.0,6.0,24.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
25%,3.0,2.0,610.0,58.0,9.0,12.0,338.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
50%,6.0,4.0,1545.0,90.0,24.0,24.0,606.0,0.0,0.0,2.0,0.0,2.0,0.0,8.0
75%,9.0,6.0,3419.0,137.0,56.0,53.0,992.0,0.0,0.0,21.0,0.0,15.0,0.0,33.0
max,12.0,7.0,9742.0,651.0,1525.0,1518.0,4962.0,1.0,1.0,1510.0,1153.0,1357.0,199.0,850.0

In [ ]:
df_retallat.info()

* Fes una anàlisi estadístic del que consideris rellevant.

In [61]:
df_retallat.corr().round(4)
# La distancia i el temps de vol ténen una relació molt forta com era d'esperar
# El enredariment de sortida està relacionat amb el d'arribada

,Month,DayOfWeek,FlightNum,AirTime,ArrDelay,DepDelay,Distance,Cancelled,Diverted,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay
Month,1.0000,0.0001,-0.0002,0.0009,-0.0009,0.0048,0.0055,0.0288,0.0065,0.0004,0.0066,0.0114,-0.0031,0.0050
DayOfWeek,0.0001,1.0000,-0.0098,0.0047,0.0061,0.0085,0.0081,0.0000,-0.0014,0.0102,0.0057,-0.0066,0.0047,0.0088
FlightNum,-0.0002,-0.0098,1.0000,-0.3412,0.0613,0.0519,-0.3568,0.0091,-0.0029,0.0557,0.0675,0.0154,-0.0028,-0.0527
AirTime,0.0009,0.0047,-0.3412,1.0000,-0.0002,-0.0028,0.9803,NaN,NaN,0.0195,-0.0183,0.0628,0.0072,-0.0220
ArrDelay,-0.0009,0.0061,0.0613,-0.0002,1.0000,0.9529,-0.0299,NaN,NaN,0.5018,0.2646,0.3876,-0.0025,0.4781
DepDelay,0.0048,0.0085,0.0519,-0.0028,0.9529,1.0000,-0.0077,0.0165,0.0229,0.5280,0.2445,0.2340,-0.0023,0.5130
Distance,0.0055,0.0081,-0.3568,0.9803,-0.0299,-0.0077,1.0000,-0.0051,0.0217,0.0284,-0.0238,0.0181,0.0070,-0.0106
Cancelled,0.0288,0.0000,0.0091,NaN,NaN,0.0165,-0.0051,1.0000,-0.0011,NaN,NaN,NaN,NaN,NaN
Diverted,0.0065,-0.0014,-0.0029,NaN,NaN,0.0229,0.0217,-0.0011,1.0000,NaN,NaN,NaN,NaN,NaN
CarrierDelay,0.0004,0.0102,0.0557,0.0195,0.5018,0.5280,0.0284,NaN,NaN,1.0000,-0.0690,-0.1195,-0.0185,-0.1783
WeatherDelay,0.0066,0.0057,0.0675,-0.0183,0.2646,0.2445,-0.0238,NaN,NaN,-0.0690,1.0000,-0.0026,-0.0075,-0.0550
NASDelay,0.0114,-0.0066,0.0154,0.0628,0.3876,0.2340,0.0181,NaN,NaN,-0.1195,-0.0026,1.0000,-0.0117,-0.1189
SecurityDelay,-0.0031,0.0047,-0.0028,0.0072,-0.0025,-0.0023,0.0070,NaN,NaN,-0.0185,-0.0075,-0.0117,1.0000,-0.0192
LateAircraftDelay,0.0050,0.0088,-0.0527,-0.0220,0.4781,0.5130,-0.0106,NaN,NaN,-0.1783,-0.0550,-0.1189,-0.0192,1.0000

In [63]:
df_retallat.cov().round(4)

,Month,DayOfWeek,FlightNum,AirTime,ArrDelay,DepDelay,Distance,Cancelled,Diverted,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay
Month,12.1440,-0.0100,1.774800e+01,-0.4893,0.1325,1.2204,5.3583,0.0016,0.0018,0.0637,0.7686,1.8298,-0.0312,0.1889
DayOfWeek,-0.0100,3.9798,-3.234810e+01,0.6036,0.9460,1.2090,8.4171,0.0000,-0.0001,0.9886,0.1633,-0.3664,0.0118,1.0889
FlightNum,17.7480,-32.3481,3.797438e+06,-45305.1933,6904.6938,5549.4218,-396135.2065,0.2895,-0.4362,4836.2460,3119.7216,982.7893,-6.5177,-4437.0907
AirTime,-0.4893,0.6036,-4.530519e+04,4731.0067,0.2804,-14.4587,38731.1210,0.0000,0.0000,49.7839,-27.6566,145.9963,1.0772,-64.7709
ArrDelay,0.1325,0.9460,6.904694e+03,0.2804,3213.4028,2868.2241,-980.1136,0.0000,0.0000,1300.8359,349.2710,809.8988,-0.3708,1212.6253
DepDelay,1.2204,1.2090,5.549422e+03,-14.4587,2868.2241,2832.8565,-269.4974,0.0120,0.0768,1348.6351,315.8983,483.9351,-0.3982,1285.8625
Distance,5.3583,8.4171,-3.961352e+05,38731.1210,-980.1136,-269.4974,330710.4356,-0.0387,0.8003,624.9553,-311.3099,358.7213,8.3482,-274.7590
Cancelled,0.0016,0.0000,2.895000e-01,0.0000,0.0000,0.0120,-0.0387,0.0003,-0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
Diverted,0.0018,-0.0001,-4.362000e-01,0.0000,0.0000,0.0768,0.8003,-0.0000,0.0040,0.0000,0.0000,0.0000,0.0000,0.0000
CarrierDelay,0.0637,0.9886,4.836246e+03,49.7839,1300.8359,1348.6351,624.9553,0.0000,0.0000,1867.0297,-65.5846,-175.8135,-1.6132,-323.1825
WeatherDelay,0.7686,0.1633,3.119722e+03,-27.6566,349.2710,315.8983,-311.3099,0.0000,0.0000,-65.5846,465.4673,-0.3903,-0.3220,-49.8994
NASDelay,1.8298,-0.3664,9.827893e+02,145.9963,809.8988,483.9351,358.7213,0.0000,0.0000,-175.8135,-0.3903,1158.3219,-0.8755,-171.3438
SecurityDelay,-0.0312,0.0118,-6.517700e+00,1.0772,-0.3708,-0.3982,8.3482,0.0000,0.0000,-1.6132,-0.3220,-0.8755,3.9990,-1.5591
LateAircraftDelay,0.1889,1.0889,-4.437091e+03,-64.7709,1212.6253,1285.8625,-274.7590,0.0000,0.0000,-323.1825,-49.8994,-171.3438,-1.5591,1758.6101

* Troba quantes dades faltants hi ha per columna.

In [64]:
df_retallat.isnull().sum()

Month                    0
DayOfWeek                0
UniqueCarrier            0
FlightNum                0
AirTime                870
ArrDelay               870
DepDelay                 0
Origin                   0
Dest                     0
Distance                 0
Cancelled                0
CancellationCode         0
Diverted                 0
CarrierDelay         71011
WeatherDelay         71011
NASDelay             71011
SecurityDelay        71011
LateAircraftDelay    71011
dtype: int64

* Crea columnes noves (velocitat mitjana del vol, si ha arribat tard o no...).

In [65]:
df_retallat['VelocitatMitjana']=df_retallat['Distance']/(df_retallat['AirTime']/60) # Velocitat mitja calculada en milles/hora

In [66]:
def funcioEnderrerit(x):
    if x == 0:
        return 0
    elif x<0:
        return 1
    else:
        return 2

In [67]:
df_retallat['VolEnrederit']=df_retallat["ArrDelay"].apply(funcioEnderrerit) # Vol en hora (0), vol avançat (1) i vol endarrerit (2)

In [68]:
df_retallat['RutaUnidireccional']=df_retallat["Origin"]+'-'+df_retallat["Dest"]

In [70]:
def funcioRuta(x,y):#comparamos el origen y el destino y el que sea mayor de los dos 
#lo ponemos en primer lugar y el menor en segundo lugar
    a=""
    if x <y:
        a= x+"-"+y
    else:
        a= y+"-"+x
    return a

In [71]:
df_retallat['RutaBidereccional']= df_retallat.apply(lambda x: funcioRuta(x["Origin"], x["Dest"]), axis = 1)

In [73]:
print(df_retallat[['VelocitatMitjana','VolEnrederit','RutaUnidireccional','RutaBidereccional']].head())

         VelocitatMitjana  VolEnrederit RutaUnidireccional RutaBidereccional
470777         346.829268             2            DAL-TUL           DAL-TUL
1068209        442.450331             2            EWR-LAS           EWR-LAS
1419631        467.524752             0            IAH-TPA           IAH-TPA
614092         449.473684             2            MFR-PHX           MFR-PHX
1569773        488.709677             2            ORD-LAS           LAS-ORD

* Fes una taula de les aerolínies amb més endarreriments acumulats.

In [74]:
df_endarrer=df_retallat[df_retallat['VolEnrederit'] == 2] #Només considerem els vols endarrerits per evitar que els vols avançats 
# compensin part del resultat.

In [75]:
df_endarrer[['UniqueCarrier', 'ArrDelay']].groupby('UniqueCarrier').sum().sort_values(by='ArrDelay', ascending=False).head(10)

                ArrDelay
UniqueCarrier
WN             1193784.0
AA              935597.0
UA              711547.0
MQ              672890.0
OO              610977.0
XE              542833.0
DL              484462.0
CO              430211.0
YV              398972.0
EV              395574.0

* Quins són els vols més llargs? I els més endarrerits? Busca les rutes més llargues i les que acumulen més retards.

In [76]:
#Top 10 de vols més llargs en distància
df_retallat[['FlightNum', 'Distance']].sort_values(by='Distance', ascending=False).drop_duplicates().head(10)

         FlightNum  Distance
1621350         15      4962
1414164         14      4962
1176974       1561      4502
182489        1282      4502
1078212       1273      4502
283355         851      4502
1264494       1560      4502
96292          850      4502
1323555          2      4243
1809929          1      4243

In [77]:
#Top 10 de vols amb enrederiments més llargs en minuts
df_retallat[['FlightNum', 'ArrDelay']].sort_values(by='ArrDelay', ascending=False).head(10)

         FlightNum  ArrDelay
163379        2398    1525.0
1214839        804    1510.0
1554448       1765    1392.0
154597        1274    1357.0
1901407       1138    1312.0
836938         491    1263.0
1029214       1226    1186.0
137568        1640    1123.0
1879242       4877    1103.0
1235949       1891    1091.0

In [78]:
#Top 10 de rutes més llargues en distància 
#(eliminem els duplicats en distància per treure la duplicitat del vol d'anada amb el de tornada)
df_retallat[['RutaBidereccional', 'Distance']].sort_values(by='Distance', ascending=False).drop_duplicates().head(10)

        RutaBidereccional  Distance
1621350           EWR-HNL      4962
1176974           ATL-HNL      4502
1323555           HNL-ORD      4243
628016            KOA-ORD      4213
956608            OGG-ORD      4184
1600429           HNL-MSP      3972
1415761           HNL-IAH      3904
1221841           DFW-HNL      3784
691538            DFW-OGG      3711
1346900           ANC-ATL      3417

In [81]:
#Top 10 de rutes amb més endarreriments 
#Només considerem els vols endarrerits per evitar que els vols avançats compensin part del resultat.
df_endarrer2=df_retallat[df_retallat['VolEnrederit'] == 2] 
df_endarrer2[['RutaBidereccional', 'ArrDelay']].groupby('RutaBidereccional').sum().sort_values(by='ArrDelay', ascending=False).head(10)

                   ArrDelay
RutaBidereccional
LGA-ORD             47038.0
EWR-ORD             46172.0
LAX-SFO             41421.0
ATL-LGA             35789.0
ATL-EWR             33409.0
DFW-ORD             32044.0
CLT-EWR             29953.0
ATL-ORD             29112.0
MSP-ORD             28831.0
ORD-PHL             28808.0

* Aporta allò que consideris rellevant.

In [82]:
# Top 10 d'aeroports de destí amb més desviacions de vols
df_retallat[['Dest', 'Diverted']].groupby('Dest').sum().sort_values(by='Diverted', ascending=False).head(10)

      Diverted
Dest
ORD         70
DFW         44
LGA         41
ATL         37
EWR         32
LAS         29
PHL         24
MDW         23
JFK         22
SAN         20

In [83]:
# Top 10 d'aeroports de destí amb més cancelació de vols
df_retallat[['Dest', 'Cancelled']].groupby('Dest').sum().sort_values(by='Cancelled', ascending=False).head(10)

      Cancelled
Dest
ORD           7
ATL           4
DFW           3
BOS           2
MKE           2
GRR           2
IAH           2
SEA           2
AUS           2
SFO           1

In [86]:
# Top 10 de vols cancelats en funció de l'aerolinea i del codi de cancel-lació
df_cancel=df_retallat[df_retallat['CancellationCode'] != 'N'] 
df_cancel=df_cancel[['UniqueCarrier','CancellationCode']]
pivotTable = df_cancel.pivot_table(index= "UniqueCarrier", columns= "CancellationCode", values="CancellationCode", 
aggfunc= 'size', fill_value=0)

In [87]:
pivotTable['Total']=pivotTable['A']+pivotTable['B']+pivotTable['C']
print(pivotTable.sort_values(by='Total', ascending=False).head(10))
#(A = carrier, B = climatologia, C = National Airspace System (NAS), D = seguretat)

CancellationCode  A  B  C  Total
UniqueCarrier
MQ                2  6  3     11
OO                3  5  0      8
YV                2  4  0      6
AA                5  0  0      5
DL                1  4  0      5
UA                3  2  0      5
NW                0  2  2      4
EV                2  0  1      3
9E                2  0  0      2
US                0  2  0      2

In [88]:
# Cancel.lacions en funció del mes
df_cancellation_month=df_retallat[['Month', 'Cancelled']].groupby('Month').agg([np.sum, np.size]).sort_values(by=[('Cancelled', 'sum')], ascending=False)
df_cancellation_month.head(5)

      Cancelled
            sum   size
Month
12           44  21002
11            9  10920
10            4  10793
1             0  19102
2             0  19500

In [89]:
# Ratio de vols per cada vol desviat per mes
df_diverted_month=df_retallat[['Month', 'Diverted']].groupby('Month').agg([np.sum, np.size])
df_diverted_month[('Diverted', 'Ratio')]=df_diverted_month[('Diverted', 'size')]/df_diverted_month[('Diverted', 'sum')]

df_diverted_month.sort_values(by=[('Diverted', 'Ratio')]).round(2)

      Diverted
           sum   size   Ratio
Month
12         152  21002  138.17
6          127  20640  162.52
8           73  16658  228.19
2           85  19500  229.41
7           73  19030  260.68
1           67  19102  285.10
11          37  10920  295.14
3           68  20623  303.28
4           50  15981  319.62
10          26  10793  415.12
5           37  15866  428.81
9           18   9885  549.17

In [93]:
# Top 10 d'enredariment per aerolinea desglossat per tipus d'endarreriment
df_delays=df_retallat[['UniqueCarrier', 'CarrierDelay','WeatherDelay','NASDelay', 'SecurityDelay','LateAircraftDelay', 'ArrDelay']].dropna()
df_delays.groupby('UniqueCarrier').sum().sort_values(by='ArrDelay', ascending=False).head(10)

,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay,ArrDelay
UniqueCarrier,,,,,,
WN,235964.0,50409.0,137117.0,2872.0,674930.0,1101292.0
AA,293778.0,43310.0,223531.0,437.0,343021.0,904077.0
UA,178209.0,22450.0,150064.0,129.0,338563.0,689415.0
MQ,179940.0,43467.0,149038.0,127.0,274532.0,647104.0
OO,167614.0,27876.0,155428.0,1283.0,232487.0,584688.0
XE,128961.0,24955.0,164789.0,1285.0,204751.0,524741.0
DL,142749.0,17259.0,131112.0,135.0,169847.0,461102.0
CO,101178.0,22085.0,155507.0,1103.0,131337.0,411210.0
YV,199614.0,23957.0,76961.0,1050.0,86291.0,387873.0
EV,169749.0,58707.0,88551.0,143.0,63490.0,380640.0

# Exercici 3
#### Exporta el dataset net i amb les noves columnes a Excel.

In [94]:
pip install openpyxl

Requirement already satisfied: openpyxl in c:\users\rauga\anaconda3\lib\site-packages (3.0.9)Note: you may need to restart the kernel to use updated packages.

Requirement already satisfied: et-xmlfile in c:\users\rauga\anaconda3\lib\site-packages (from openpyxl) (1.1.0)

In [95]:
df_retallat.to_excel('D:\Dades Aerolinies.xlsx', sheet_name='Dades', index = False)